export const LANGUAGE_MAP = {
  js: 'JavaScript',
  ts: 'TypeScript',
  md: 'Markdown',
  markdown: 'Markdown',
  cpp: 'C++',
  c: 'C',
  java: 'Java',
  python: 'Python',
  py: 'Python',
  php: 'PHP',
  rust: 'Rust',
  rs: 'Rust',
  xml: 'XML',
  sql: 'SQL',
  json: 'JSON',
  'c#': 'C#',
  cs: 'C#',
  sass: 'Sass',
  less: 'Less',
  vue: 'Vue',
  angular: 'Angular',
  go: 'Go',
  golang: 'Go',
  html: 'HTML',
  css: 'CSS',
  scss: 'SCSS',
  shell: 'Shell',
  bash: 'Bash',
  sh: 'Shell',
  yaml: 'YAML',
  yml: 'YAML',
  dockerfile: 'Dockerfile',
  // ... добавь свои
};
export const PROG_LANGS = [
    '?', '?',
    'JavaScript',
    'TypeScript',
    'Markdown',
    'C++',
    'Java',
    'Python',
    'PHP',
    'Rust',
    'XML',
    'SQL',
    'JSON',
    'C#',
    'C',
    'Sass',
    'Less',
    'Vue',
    'Angular',
    'Go',
    'HTML',
    'CSS',
    'SCSS',
]